### ISSUE TITLE
Nimble parsing error

### ISSUE THREAD

**Issue by elcritch** [nim-lang/atlas#111]
Nimble parser needs to handle this properly:

```
/Users/jaremycreechley/.atlas/nim-testutils/testutils.nimble(10, 17) Error: assignments to 'srcDir' must be string literals
```

Caused by `#` in:

```nim
bin           = @["ntu"]
#srcDir        = "testutils"
```

**Comment by elcritch** [comment]
Also this breaks as well:


```nim
equires "nim >= 1.6.0",
         "stew",
         "unittest2"
```

**Comment by ringabout** [comment]
How to reproduce it? `atlas extract testutils.nimble` works for me. Do you happen to know the commands to reproduce the issue?

**Comment by ringabout** [comment]
Weird, I had reprodued it yesterday with `atlas use testutils`. But I had a hard time reproducing it today. @elcritch did you happen to know the steps to reproduce it?

**Comment by elcritch** [comment]
I'm not sure this is related to Atlas. I added a unit test and the nimble parser works fine. 

These parsing errors must be coming from somewhere else. I haven't figured out where yet though.

**Comment by ringabout** [comment]
They are not errors though, which don't stop the version selection. Well, I will turn them into warnings or eliminate them anyways

**Comment by elcritch** [comment]
Do you know where they're coming from? It doesn't look like it's using the normal Atlas logging.

**Comment by elcritch** [comment]
> They are not errors though, which don't stop the version selection. Well, I will turn them into warnings or eliminate them anyways

Yah the problem is from a user perspective you just see error messages. Warnings would be better though. Otherwise it's not clear if things are working properly or not.
