### ISSUE TITLE
Refactor AtlasContext into it's own file?

### ISSUE THREAD

**Issue by elcritch** [nim-lang/atlas#22]
Would it make sense to move AtlasContext into it's own module like `context.nim`? 

It'd let the main `atlas.nim` be broken up into more self contained modules -- something like a `cloning.nim` module for handling that functionality. I think it'd help making unit tests as well and to use logging more places.

**Comment by Araq** [comment]
The refactoring is indirectly outlined in this issue tracker. There the dependency graph plus a walker. Then there are extractors, fetchers and builders.

**Comment by elcritch** [comment]
Ah yes, I've seen those but they all depend to some degree on the AtlasContext. I was asking more specifically that since AtlasContext is a common piece to those other modules/features that'd it'd make sense to move it out of atlas.nim so it could be reused.
