### ISSUE TITLE
add support for namespaces

### ISSUE THREAD

**Issue by Araq** [nim-lang/atlas#5]
If there are two projects of the same name but of different origin (i.e coming from different URLs), namespace the projects. This means to turn the project name into `$project.$author.$github`.

**Comment by Araq** [comment]
Ping @elcritch 

You implemented this, right?

**Comment by elcritch** [comment]
@Araq yes, it's implemented. I believe some of the integration tests catch this as well. 

Ah, yes: `./tests/ws_integration/expected/nim.cfg:--path:"redis.zedeus.github.com/src"`.
