### ISSUE TITLE
Provide a section in the readme on how to use atlas to install Nim itself.

### ISSUE THREAD

**Issue by treeform** [nim-lang/atlas#61]
[This comment](https://forum.nim-lang.org/t/10373#69087):
>> Choosenim is the best way to have the latest Nim version around while still being able to jump to devel versions or a local copy.

> Is it though? Atlas can do the same already.

This comment seems to imply that you can use atlas as a choosenim replacement. There is anything about this in the README? How does it work? What commands does it need to run?

**Comment by Araq** [comment]
Via `atlas env 2.0.0`. Atlas gives you virtual Nim environments.
