### ISSUE TITLE
[request | question] Ability to connect atlas to the root toolchain of the system

### ISSUE THREAD

**Issue by heysokam** [nim-lang/atlas#64]
I've tried setting up atlas for a project, but I don't know if I like that there is no way (that I know of) to connect an atlas workspace to the root toolchain folder of the host system (or any other arbitrary folder).

I understand if this is by design, and it does make a lot of sense if this is the case.

What I was thinking is having the option to (explicitly, manually) setup paths where atlas can search for dependencies, so that the same libraries don't end up duplicated 10 times because of having 10 different workspaces.

My idea would be:
```md
1. Setup alternative folder to search for (explicitly)
2. `atlas use mydepend`
2.1 atlas searches for the dependency in the alternative folders, if they are any
---> does not redownload the library, just uses the ones in the other folder
---> choose by prioritizing the last folder found, like nim.cfg does (or first, or whatever other rule)
2.2 no alternatives found. atlas continues with the current behavior where the libraries are duplicated once for each workspace
```

That would be my feature request if this is not possible.
Or just my _question_ if the feature exists and I haven't found it (sorry if that's the case).

**Comment by heysokam** [comment]
Oh, so you mean I could add the system toolkit folder to the nim.cfg file?
Didn't think that would work

**Comment by Araq** [comment]
> Oh, so you mean I could add the system toolkit folder to the nim.cfg file?

Yes, that works.

> Would it be possible to do that for the workspace itself, in some way?

Yes, create a `nim.cfg` in the workspace.

> Also, would that stop atlas from duplicating the folders when a dependency is asked for?

Yes, if the dependency is not in your .nimble file.
