### ISSUE TITLE
Use "shallow" git cloning when pulling dependencies

### ISSUE THREAD

**Issue by ZoomRmc** [nim-lang/atlas#65]
Consider using `git clone --depth=1` for pulling dependencies.

This:
- Saves a non-negligible amount of space dropping what in most cases amounts to dead weight.
- Speeds-up the cloning process.

For further possible interacting with the pulled repos there's `git fetch --unshallow`.

**Comment by elcritch** [comment]
This would be nice. I could add this, but do you know the command(s) for git submodules? 

Does `git clone --depth=1` fetch the tags / branch names too? (I forget). That could bork version checking unless there's a way to fetch them too.

**Comment by elcritch** [comment]
Heya, I was able to replicate your issue. Looking into it.

**Comment by elcritch** [comment]
Ah, ok so definitely some issues with Atlas and the way I have Figuro setup. Been putting it off, but easy-ish to fix.

**Comment by ZoomRmc** [comment]
Closed with #67

@elcritch I don't think it does fetch anything besides the top commit. For example, using it with `--branch <TAG>` uses the tag name only and leaves a detached HEAD.
