### ISSUE TITLE
Possible interest support for cross compiling?

### ISSUE THREAD

**Issue by elcritch** [nim-lang/atlas#8]
I've spent way more time than I care to think about trying to figure out a generic cross compiling scheme. `conan` and `conda` sorta offer this but not very well. 

All of that said, Nim already has decent cross compiling support but it's just not very centralized and requires each dev to sorta re-invent things. It also depends on each dev to figure out how to get and install cross compilers. 

It'd be amazing if `atlas` could provide a way to provide a sequence like "install cross-xc compilers then use them to build" sequence. From what little I've seen of Atlas this wouldn't seem to impractical too add. Especially if it could be added as just another builder / extractor with possibly a bit of sugar on the nim.cfg side. Perhaps another concept of a "provider" could be added too, e.g. recipe for building and installing a specific Nim compiler or non-Nim compile tools. 

I'm creating this issue to find out if others would be interested in as well. It's something I'd be keen on adding if it'd be accepted. Though it'd have to be non-invasive and not complicate the simple build path, otherwise I think it'd be going down the wrong path.

**Comment by Araq** [comment]
I think this is currently way outside of the scope of Atlas and first steps should be to make configuration easier in the Nim compiler itself. We should also have a dedicated document about this topic.

**Comment by elcritch** [comment]
Great, I agree with all of those. Though I do think Atlas could be useful for XC if we get builders / extractors / etc in place. 

I'll close this for now noting that it'll require further discussion at some point.
